{
  imports = [
    ./neodev.nix
    ./colorscheme
    ./alpha.nix
    ./lualine
    ./gitsigns.nix
    ./oil.nix
    ./auto-hlsearch.nix
    ./colorizer.nix
    ./undotree.nix
    ./tmux-navigator.nix
    ./lazygit.nix
    ./glow.nix
    ./autopairs.nix
    ./lint.nix
    ./cmp
    ./telescope
    ./comment.nix
    ./sleuth.nix
    ./treesitter
    ./conform.nix
    ./harpoon
    ./indent-blankline.nix
  ];
}
